name: superball
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  signals: ^6.3.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  flame: ^1.34.0
  flame_forge2d: ^0.19.2+2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.2.4
  build_runner: any
  json_serializable: any
  injectable_generator: any
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/projectiles/
    - assets/images/
